### ISSUE TITLE
Quick Improvements

### ISSUE THREAD

**Issue by meschw04** [markgraves/leat#7]
Hello @markgraves, I went ahead and cloned the repo and tried `pytest` on your unit tests. Here are a few quick things I think you could do. I'd make a fork and submit a PR, but this stuff is all pretty simple:
- Add `setup.py` in main folder. It should contain something like the following.
```
import os
import sys
from setuptools import setup, Extension, find_packages

version_dict = {}
with open("leat/version.py") as fp:
    exec(fp.read(), version_dict)
__version__ = version_dict['__version__']

setup(
    name='leat',
    version=__version__,
    description='Light-weight ethical auditing tool for data-centric developers',
    url='https://github.com/markgraves/leat',
    license='PROPRIETARY',
    packages=find_packages(),
    include_package_data=True,
)
```
- Add `leat/version.py` which just contains the line `__version__ = '0.1'`
- Add the `python-pptx` package to `requirements.txt`.

If you make these changes, the leat package will be pip-installable (I do not think it is right now, it needs either a `setup.py` or a `.toml`) and `pytest` will work out of the gate with the update to `requirements.txt`.

HTH,

Marcus

**Comment by markgraves** [comment]
Thanks, @meschw04. I made these updates.

**Comment by meschw04** [comment]
Closed based on PR: https://github.com/markgraves/leat/pull/9
